### ISSUE TITLE
budget

### ISSUE THREAD

**Issue by timm** [opensciences/NSF-small18a-humansAndAi#8]
add $20K to budget for hard dives

**Comment by timm** [comment]
suvdodeep justify hard drive cost

**Comment by timm** [comment]
What happens at 24000?

Urgent: need this monday

**Comment by Suvodeep90** [comment]
It usages a RAID10 storage, having redundant storage with an increased data access speed.So it have 4 8TB storage.

**Comment by rahlk** [comment]
| Software      | License Cost                                        |
|---------------|-----------------------------------------------------|
| Understand    | Free for Education (Max 50. process concurrently)   |
| SonarQube     | $4000 per/instance/year (Total $12,000 for 3 years) |
| ElasticSearch | Open source Free                                    |
| Total | +$12,000                                     |

**Comment by Suvodeep90** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/31140098/48386142-01509380-e6bf-11e8-961f-9b9f9afbdaef.png">
